/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as PoolPoolIdRouteImport } from './routes/pool.$poolId'
import { Route as DailyStatKeyRouteImport } from './routes/daily_.stat.$key'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolPoolIdRoute = PoolPoolIdRouteImport.update({
  id: '/pool/$poolId',
  path: '/pool/$poolId',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyStatKeyRoute = DailyStatKeyRouteImport.update({
  id: '/daily_/stat/$key',
  path: '/daily/stat/$key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/pool/$poolId': typeof PoolPoolIdRoute
  '/daily/stat/$key': typeof DailyStatKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/pool/$poolId': typeof PoolPoolIdRoute
  '/daily/stat/$key': typeof DailyStatKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/pool/$poolId': typeof PoolPoolIdRoute
  '/daily_/stat/$key': typeof DailyStatKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/daily' | '/pool/$poolId' | '/daily/stat/$key'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/daily' | '/pool/$poolId' | '/daily/stat/$key'
  id: '__root__' | '/' | '/daily' | '/pool/$poolId' | '/daily_/stat/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DailyRoute: typeof DailyRoute
  PoolPoolIdRoute: typeof PoolPoolIdRoute
  DailyStatKeyRoute: typeof DailyStatKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pool/$poolId': {
      id: '/pool/$poolId'
      path: '/pool/$poolId'
      fullPath: '/pool/$poolId'
      preLoaderRoute: typeof PoolPoolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily_/stat/$key': {
      id: '/daily_/stat/$key'
      path: '/daily/stat/$key'
      fullPath: '/daily/stat/$key'
      preLoaderRoute: typeof DailyStatKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DailyRoute: DailyRoute,
  PoolPoolIdRoute: PoolPoolIdRoute,
  DailyStatKeyRoute: DailyStatKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
